// Copyright (c) .NET Foundation and Contributors. All rights reserved. Licensed under the University of Illinois/NCSA Open Source License. See LICENSE.txt in the project root for license information.
// Ported from https://github.com/microsoft/ClangSharp/blob/main/sources/libClangSharp

namespace ClangSharp.Interop
{
    public enum CX_OverloadedOperatorKind
    {
        CX_OO_Invalid,
        CX_OO_New,
        CX_OO_Delete,
        CX_OO_Array_New,
        CX_OO_Array_Delete,
        CX_OO_Plus,
        CX_OO_Minus,
        CX_OO_Star,
        CX_OO_Slash,
        CX_OO_Percent,
        CX_OO_Caret,
        CX_OO_Amp,
        CX_OO_Pipe,
        CX_OO_Tilde,
        CX_OO_Exclaim,
        CX_OO_Equal,
        CX_OO_Less,
        CX_OO_Greater,
        CX_OO_PlusEqual,
        CX_OO_MinusEqual,
        CX_OO_StarEqual,
        CX_OO_SlashEqual,
        CX_OO_PercentEqual,
        CX_OO_CaretEqual,
        CX_OO_AmpEqual,
        CX_OO_PipeEqual,
        CX_OO_LessLess,
        CX_OO_GreaterGreater,
        CX_OO_LessLessEqual,
        CX_OO_GreaterGreaterEqual,
        CX_OO_EqualEqual,
        CX_OO_ExclaimEqual,
        CX_OO_LessEqual,
        CX_OO_GreaterEqual,
        CX_OO_Spaceship,
        CX_OO_AmpAmp,
        CX_OO_PipePipe,
        CX_OO_PlusPlus,
        CX_OO_MinusMinus,
        CX_OO_Comma,
        CX_OO_ArrowStar,
        CX_OO_Arrow,
        CX_OO_Call,
        CX_OO_Subscript,
        CX_OO_Conditional,
        CX_OO_Coawait,
    }
}
