// Copyright (c) .NET Foundation and Contributors. All Rights Reserved. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using NUnit.Framework;
using System.Xml.Linq;
using ClangSharp.Interop;
using static ClangSharp.Interop.CXTranslationUnit_Flags;

namespace ClangSharp.UnitTests;

public abstract class PInvokeGeneratorTest
{
    protected const string DefaultInputFileName = "ClangUnsavedFile.h";
    protected const string DefaultLibraryPath = "ClangSharpPInvokeGenerator";
    protected const string DefaultNamespaceName = "ClangSharp.Test";

    protected const CXTranslationUnit_Flags DefaultTranslationUnitFlags = CXTranslationUnit_IncludeAttributedTypes          // Include attributed types in CXType
                                                                        | CXTranslationUnit_VisitImplicitAttributes         // Implicit attributes should be visited
                                                                        | CXTranslationUnit_DetailedPreprocessingRecord;
    protected const string DefaultCStandard = "c17";
    protected const string DefaultCppStandard = "c++17";

    protected static readonly string[] DefaultCClangCommandLineArgs =
    [
        $"-std={DefaultCStandard}",                             // The input files should be compiled for C 17
        "-xc",                                  // The input files are C
    ];

    protected static readonly string[] DefaultCppClangCommandLineArgs =
    [
        $"-std={DefaultCppStandard}",                           // The input files should be compiled for C++ 17
        "-xc++",                                // The input files are C++
        "-Wno-pragma-once-outside-header",      // We are processing files which may be header files
        "-Wno-c++11-narrowing"
    ];

    protected static string EscapeXml(string value) => new XText(value).ToString();

    protected static Task ValidateGeneratedCSharpPreviewWindowsBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.CSharp, PInvokeGeneratorConfigurationOptions.GeneratePreviewCode | PInvokeGeneratorConfigurationOptions.None | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedCSharpPreviewUnixBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.CSharp, PInvokeGeneratorConfigurationOptions.GeneratePreviewCode | PInvokeGeneratorConfigurationOptions.GenerateUnixTypes | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedCSharpLatestWindowsBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard, IReadOnlyDictionary<string, string>? remappedTypeNames = null, IReadOnlyDictionary<string, string>? remappedFieldNames = null)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.CSharp, PInvokeGeneratorConfigurationOptions.GenerateLatestCode | PInvokeGeneratorConfigurationOptions.None | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard, remappedTypeNames, remappedFieldNames);

    protected static Task ValidateGeneratedCSharpLatestUnixBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.CSharp, PInvokeGeneratorConfigurationOptions.GenerateLatestCode | PInvokeGeneratorConfigurationOptions.GenerateUnixTypes | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedCSharpDefaultWindowsBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.CSharp, PInvokeGeneratorConfigurationOptions.None | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedCSharpDefaultUnixBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.CSharp, PInvokeGeneratorConfigurationOptions.GenerateUnixTypes | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedCSharpCompatibleWindowsBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.CSharp, PInvokeGeneratorConfigurationOptions.GenerateCompatibleCode | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedCSharpCompatibleUnixBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.CSharp, PInvokeGeneratorConfigurationOptions.GenerateCompatibleCode | PInvokeGeneratorConfigurationOptions.GenerateUnixTypes | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedXmlPreviewWindowsBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.Xml, PInvokeGeneratorConfigurationOptions.GeneratePreviewCode | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedXmlPreviewUnixBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.Xml, PInvokeGeneratorConfigurationOptions.GeneratePreviewCode | PInvokeGeneratorConfigurationOptions.GenerateUnixTypes | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedXmlLatestWindowsBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.Xml, PInvokeGeneratorConfigurationOptions.GenerateLatestCode | PInvokeGeneratorConfigurationOptions.None | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedXmlLatestUnixBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.Xml, PInvokeGeneratorConfigurationOptions.GenerateLatestCode | PInvokeGeneratorConfigurationOptions.GenerateUnixTypes | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedXmlDefaultWindowsBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.Xml, PInvokeGeneratorConfigurationOptions.None | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedXmlDefaultUnixBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.Xml, PInvokeGeneratorConfigurationOptions.GenerateUnixTypes | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedXmlCompatibleWindowsBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.Xml, PInvokeGeneratorConfigurationOptions.GenerateCompatibleCode | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    protected static Task ValidateGeneratedXmlCompatibleUnixBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorConfigurationOptions additionalConfigOptions = PInvokeGeneratorConfigurationOptions.None, string[]? excludedNames = null, IReadOnlyDictionary<string, string>? remappedNames = null, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes = null, IReadOnlyDictionary<string, string>? withCallConvs = null, IReadOnlyDictionary<string, string>? withClasses = null, IReadOnlyDictionary<string, string>? withLibraryPaths = null, IReadOnlyDictionary<string, string>? withNamespaces = null, string[]? withSetLastErrors = null, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs = null, IReadOnlyDictionary<string, string>? withTypes = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings = null, IReadOnlyDictionary<string, string>? withPackings = null, IEnumerable<Diagnostic>? expectedDiagnostics = null, string libraryPath = DefaultLibraryPath, string[]? commandLineArgs = null, string language = "c++", string languageStandard = DefaultCppStandard)
        => ValidateGeneratedBindingsAsync(inputContents, expectedOutputContents, PInvokeGeneratorOutputMode.Xml, PInvokeGeneratorConfigurationOptions.GenerateCompatibleCode | PInvokeGeneratorConfigurationOptions.GenerateUnixTypes | additionalConfigOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard);

    private static async Task ValidateGeneratedBindingsAsync(string inputContents, string expectedOutputContents, PInvokeGeneratorOutputMode outputMode, PInvokeGeneratorConfigurationOptions configOptions, string[]? excludedNames, IReadOnlyDictionary<string, string>? remappedNames, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes, IReadOnlyDictionary<string, string>? withCallConvs, IReadOnlyDictionary<string, string>? withClasses, IReadOnlyDictionary<string, string>? withLibraryPaths, IReadOnlyDictionary<string, string>? withNamespaces, string[]? withSetLastErrors, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs, IReadOnlyDictionary<string, string>? withTypes, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings, IReadOnlyDictionary<string, string>? withPackings, IEnumerable<Diagnostic>? expectedDiagnostics, string libraryPath, string[]? commandLineArgs, string language, string languageStandard, IReadOnlyDictionary<string, string>? remappedTypeNames = null, IReadOnlyDictionary<string, string>? remappedFieldNames = null)
    {
        var actualOutputContents = await GenerateBindingsAsync(inputContents, outputMode, configOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard, remappedTypeNames, remappedFieldNames).ConfigureAwait(false);
        Assert.That(actualOutputContents, Is.EqualTo(expectedOutputContents));
    }

    // Convenience wrapper over GenerateBindingsWithTestOutputAsync that returns only the primary bindings text,
    // used by both the inline-string harness and the checked-in baseline harness (neither asserts test output).
    internal static async Task<string> GenerateBindingsAsync(string inputContents, PInvokeGeneratorOutputMode outputMode, PInvokeGeneratorConfigurationOptions configOptions, string[]? excludedNames, IReadOnlyDictionary<string, string>? remappedNames, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes, IReadOnlyDictionary<string, string>? withCallConvs, IReadOnlyDictionary<string, string>? withClasses, IReadOnlyDictionary<string, string>? withLibraryPaths, IReadOnlyDictionary<string, string>? withNamespaces, string[]? withSetLastErrors, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs, IReadOnlyDictionary<string, string>? withTypes, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings, IReadOnlyDictionary<string, string>? withPackings, IEnumerable<Diagnostic>? expectedDiagnostics, string libraryPath, string[]? commandLineArgs, string language, string languageStandard, IReadOnlyDictionary<string, string>? remappedTypeNames = null, IReadOnlyDictionary<string, string>? remappedFieldNames = null, string? typePrefixToStrip = null, IReadOnlyDictionary<string, string>? withEnumMemberStrip = null, string? withConditional = null, string[]? withEqualityMembers = null, IReadOnlyDictionary<string, Guid>? withGuids = null, string[]? withoutSetLastErrors = null, IReadOnlyCollection<string>? withoutCallConvs = null, string[]? withConstantFoldedValues = null, string[]? withoutConstantFoldedValues = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withBases = null)
    {
        var (actualOutputContents, _) = await GenerateBindingsWithTestOutputAsync(inputContents, outputMode, configOptions, excludedNames, remappedNames, withAccessSpecifiers, withAttributes, withCallConvs, withClasses, withLibraryPaths, withNamespaces, withSetLastErrors, withTransparentStructs, withTypes, withUsings, withPackings, expectedDiagnostics, libraryPath, commandLineArgs, language, languageStandard, remappedTypeNames, remappedFieldNames, typePrefixToStrip, withEnumMemberStrip, withConditional, withEqualityMembers, withGuids, withoutSetLastErrors, withoutCallConvs, withConstantFoldedValues, withoutConstantFoldedValues, withBases).ConfigureAwait(false);
        return actualOutputContents;
    }

    // Same generator core as GenerateBindingsAsync, but additionally captures the auxiliary test output that the
    // generator emits when GenerateTestsNUnit/GenerateTestsXUnit are set. The regular bindings and the generated
    // tests are written to separate output streams (keyed off the config's OutputLocation vs TestOutputLocation),
    // so both can be validated independently. TestOutputContents is the empty string when no test output was
    // generated (either because tests weren't requested or nothing in the input produced any).
    internal static async Task<(string OutputContents, string TestOutputContents)> GenerateBindingsWithTestOutputAsync(string inputContents, PInvokeGeneratorOutputMode outputMode, PInvokeGeneratorConfigurationOptions configOptions, string[]? excludedNames, IReadOnlyDictionary<string, string>? remappedNames, IReadOnlyDictionary<string, AccessSpecifier>? withAccessSpecifiers, IReadOnlyDictionary<string, IReadOnlyList<string>>? withAttributes, IReadOnlyDictionary<string, string>? withCallConvs, IReadOnlyDictionary<string, string>? withClasses, IReadOnlyDictionary<string, string>? withLibraryPaths, IReadOnlyDictionary<string, string>? withNamespaces, string[]? withSetLastErrors, IReadOnlyDictionary<string, (string, PInvokeGeneratorTransparentStructKind)>? withTransparentStructs, IReadOnlyDictionary<string, string>? withTypes, IReadOnlyDictionary<string, IReadOnlyList<string>>? withUsings, IReadOnlyDictionary<string, string>? withPackings, IEnumerable<Diagnostic>? expectedDiagnostics, string libraryPath, string[]? commandLineArgs, string language, string languageStandard, IReadOnlyDictionary<string, string>? remappedTypeNames = null, IReadOnlyDictionary<string, string>? remappedFieldNames = null, string? typePrefixToStrip = null, IReadOnlyDictionary<string, string>? withEnumMemberStrip = null, string? withConditional = null, string[]? withEqualityMembers = null, IReadOnlyDictionary<string, Guid>? withGuids = null, string[]? withoutSetLastErrors = null, IReadOnlyCollection<string>? withoutCallConvs = null, string[]? withConstantFoldedValues = null, string[]? withoutConstantFoldedValues = null, IReadOnlyDictionary<string, IReadOnlyList<string>>? withBases = null)
    {
        Assert.That(DefaultInputFileName, Does.Exist);
        commandLineArgs ??= DefaultCppClangCommandLineArgs;

        configOptions |= PInvokeGeneratorConfigurationOptions.GenerateMacroBindings;

        var generatesTests = (configOptions & (PInvokeGeneratorConfigurationOptions.GenerateTestsNUnit | PInvokeGeneratorConfigurationOptions.GenerateTestsXUnit)) != 0;

        using var outputStream = new MemoryStream();
        using var testOutputStream = new MemoryStream();
        using var unsavedFile = CXUnsavedFile.Create(DefaultInputFileName, inputContents);

        var unsavedFiles = new CXUnsavedFile[] { unsavedFile };
        var config = new PInvokeGeneratorConfiguration(language, languageStandard, DefaultNamespaceName, Path.GetRandomFileName(), headerFile: null, outputMode, configOptions) {
            DefaultClass = null,
            ExcludedNames = excludedNames,
            IncludedNames = null,
            LibraryPath = libraryPath,
            MethodPrefixToStrip = null,
            TypePrefixToStrip = typePrefixToStrip,
            RemappedNames = remappedNames,
            RemappedTypeNames = remappedTypeNames,
            RemappedFieldNames = remappedFieldNames,
            TraversalNames = null,
            TestOutputLocation = generatesTests ? Path.GetRandomFileName() : null,
            WithAccessSpecifiers = withAccessSpecifiers,
            WithAttributes = withAttributes,
            WithBases = withBases,
            WithCallConvs = withCallConvs,
            WithoutCallConvs = withoutCallConvs,
            WithClasses = withClasses,
            WithEnumMemberStrip = withEnumMemberStrip,
            WithEqualityMembers = withEqualityMembers,
            WithLibraryPaths = withLibraryPaths,
            WithManualImports = null,
            WithNamespaces = withNamespaces,
            WithSetLastErrors = withSetLastErrors,
            WithoutSetLastErrors = withoutSetLastErrors,
            WithSuppressGCTransitions = null,
            WithTransparentStructs = withTransparentStructs,
            WithTypes = withTypes,
            WithUsings = withUsings,
            WithPackings = withPackings,
            WithConditional = withConditional,
            WithConstantFoldedValues = withConstantFoldedValues,
            WithoutConstantFoldedValues = withoutConstantFoldedValues,
            WithGuids = withGuids,
        };

        var testOutputLocation = config.TestOutputLocation;

        Stream OutputStreamFactory(string path)
        {
            return generatesTests && string.Equals(path, testOutputLocation, StringComparison.Ordinal) ? testOutputStream : outputStream;
        }

        using (var pinvokeGenerator = new PInvokeGenerator(config, OutputStreamFactory))
        {
            var handle = CXTranslationUnit.Parse(pinvokeGenerator.IndexHandle, DefaultInputFileName, commandLineArgs, unsavedFiles, DefaultTranslationUnitFlags);

            using var translationUnit = TranslationUnit.GetOrCreate(handle);
            Debug.Assert(translationUnit is not null);

            pinvokeGenerator.GenerateBindings(translationUnit, DefaultInputFileName, commandLineArgs, DefaultTranslationUnitFlags);

            if (expectedDiagnostics is null)
            {
                Assert.That(pinvokeGenerator.Diagnostics, Is.Empty);
            }
            else
            {
                Assert.That(pinvokeGenerator.Diagnostics, Is.EqualTo(expectedDiagnostics));
            }
        }
        outputStream.Position = 0;

        using var streamReader = new StreamReader(outputStream);
        var actualOutputContents = await streamReader.ReadToEndAsync().ConfigureAwait(false);

        testOutputStream.Position = 0;
        using var testStreamReader = new StreamReader(testOutputStream);
        var actualTestOutputContents = await testStreamReader.ReadToEndAsync().ConfigureAwait(false);

        return (actualOutputContents, actualTestOutputContents);
    }
}
