// Copyright (c) .NET Foundation and Contributors. All Rights Reserved. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from https://github.com/dotnet/clangsharp/blob/main/sources/libClangSharp

namespace ClangSharp.Interop;

public enum CX_DeclKind
{
    CX_DeclKind_Invalid,
    CX_DeclKind_TranslationUnit,
    CX_DeclKind_TopLevelStmt,
    CX_DeclKind_RequiresExprBody,
    CX_DeclKind_OutlinedFunction,
    CX_DeclKind_LinkageSpec,
    CX_DeclKind_ExternCContext,
    CX_DeclKind_Export,
    CX_DeclKind_Captured,
    CX_DeclKind_Block,
    CX_DeclKind_StaticAssert,
    CX_DeclKind_PragmaDetectMismatch,
    CX_DeclKind_PragmaComment,
    CX_DeclKind_OpenACCRoutine,
    CX_DeclKind_OpenACCDeclare,
    CX_DeclKind_ObjCPropertyImpl,
    CX_DeclKind_OMPThreadPrivate,
    CX_DeclKind_OMPRequires,
    CX_DeclKind_OMPGroupPrivate,
    CX_DeclKind_OMPAllocate,
    CX_DeclKind_ObjCMethod,
    CX_DeclKind_ObjCProtocol,
    CX_DeclKind_ObjCInterface,
    CX_DeclKind_ObjCImplementation,
    CX_DeclKind_ObjCCategoryImpl,
    CX_DeclKind_FirstObjCImpl = 23,
    CX_DeclKind_LastObjCImpl = 24,
    CX_DeclKind_ObjCCategory,
    CX_DeclKind_FirstObjCContainer = 21,
    CX_DeclKind_LastObjCContainer = 25,
    CX_DeclKind_HLSLBuffer,
    CX_DeclKind_OMPDeclareReduction,
    CX_DeclKind_OMPDeclareMapper,
    CX_DeclKind_UnresolvedUsingValue,
    CX_DeclKind_UnnamedGlobalConstant,
    CX_DeclKind_TemplateParamObject,
    CX_DeclKind_MSGuid,
    CX_DeclKind_IndirectField,
    CX_DeclKind_EnumConstant,
    CX_DeclKind_Function,
    CX_DeclKind_CXXMethod,
    CX_DeclKind_CXXDestructor,
    CX_DeclKind_CXXConversion,
    CX_DeclKind_CXXConstructor,
    CX_DeclKind_FirstCXXMethod = 36,
    CX_DeclKind_LastCXXMethod = 39,
    CX_DeclKind_CXXDeductionGuide,
    CX_DeclKind_FirstFunction = 35,
    CX_DeclKind_LastFunction = 40,
    CX_DeclKind_Var,
    CX_DeclKind_VarTemplateSpecialization,
    CX_DeclKind_VarTemplatePartialSpecialization,
    CX_DeclKind_FirstVarTemplateSpecialization = 42,
    CX_DeclKind_LastVarTemplateSpecialization = 43,
    CX_DeclKind_ParmVar,
    CX_DeclKind_OMPCapturedExpr,
    CX_DeclKind_ImplicitParam,
    CX_DeclKind_Decomposition,
    CX_DeclKind_FirstVar = 41,
    CX_DeclKind_LastVar = 47,
    CX_DeclKind_NonTypeTemplateParm,
    CX_DeclKind_MSProperty,
    CX_DeclKind_Field,
    CX_DeclKind_ObjCIvar,
    CX_DeclKind_ObjCAtDefsField,
    CX_DeclKind_FirstField = 50,
    CX_DeclKind_LastField = 52,
    CX_DeclKind_FirstDeclarator = 35,
    CX_DeclKind_LastDeclarator = 52,
    CX_DeclKind_Binding,
    CX_DeclKind_FirstValue = 27,
    CX_DeclKind_LastValue = 53,
    CX_DeclKind_UsingShadow,
    CX_DeclKind_ConstructorUsingShadow,
    CX_DeclKind_FirstUsingShadow = 54,
    CX_DeclKind_LastUsingShadow = 55,
    CX_DeclKind_UsingPack,
    CX_DeclKind_UsingDirective,
    CX_DeclKind_UnresolvedUsingIfExists,
    CX_DeclKind_Record,
    CX_DeclKind_CXXRecord,
    CX_DeclKind_ClassTemplateSpecialization,
    CX_DeclKind_ClassTemplatePartialSpecialization,
    CX_DeclKind_FirstClassTemplateSpecialization = 61,
    CX_DeclKind_LastClassTemplateSpecialization = 62,
    CX_DeclKind_FirstCXXRecord = 60,
    CX_DeclKind_LastCXXRecord = 62,
    CX_DeclKind_FirstRecord = 59,
    CX_DeclKind_LastRecord = 62,
    CX_DeclKind_Enum,
    CX_DeclKind_FirstTag = 59,
    CX_DeclKind_LastTag = 63,
    CX_DeclKind_UnresolvedUsingTypename,
    CX_DeclKind_Typedef,
    CX_DeclKind_TypeAlias,
    CX_DeclKind_ObjCTypeParam,
    CX_DeclKind_FirstTypedefName = 65,
    CX_DeclKind_LastTypedefName = 67,
    CX_DeclKind_TemplateTypeParm,
    CX_DeclKind_FirstType = 59,
    CX_DeclKind_LastType = 68,
    CX_DeclKind_TemplateTemplateParm,
    CX_DeclKind_VarTemplate,
    CX_DeclKind_TypeAliasTemplate,
    CX_DeclKind_FunctionTemplate,
    CX_DeclKind_ClassTemplate,
    CX_DeclKind_FirstRedeclarableTemplate = 70,
    CX_DeclKind_LastRedeclarableTemplate = 73,
    CX_DeclKind_Concept,
    CX_DeclKind_BuiltinTemplate,
    CX_DeclKind_FirstTemplate = 69,
    CX_DeclKind_LastTemplate = 75,
    CX_DeclKind_ObjCProperty,
    CX_DeclKind_ObjCCompatibleAlias,
    CX_DeclKind_Namespace,
    CX_DeclKind_NamespaceAlias,
    CX_DeclKind_FirstNamespaceBase = 78,
    CX_DeclKind_LastNamespaceBase = 79,
    CX_DeclKind_Label,
    CX_DeclKind_HLSLRootSignature,
    CX_DeclKind_UsingEnum,
    CX_DeclKind_Using,
    CX_DeclKind_FirstBaseUsing = 82,
    CX_DeclKind_LastBaseUsing = 83,
    CX_DeclKind_FirstNamed = 20,
    CX_DeclKind_LastNamed = 83,
    CX_DeclKind_LifetimeExtendedTemporary,
    CX_DeclKind_Import,
    CX_DeclKind_ImplicitConceptSpecialization,
    CX_DeclKind_FriendTemplate,
    CX_DeclKind_Friend,
    CX_DeclKind_FileScopeAsm,
    CX_DeclKind_Empty,
    CX_DeclKind_AccessSpec,
    CX_DeclKind_FirstDecl = 1,
    CX_DeclKind_LastDecl = 91,
}
