// Copyright (c) .NET Foundation and Contributors. All Rights Reserved. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from https://github.com/dotnet/clangsharp/blob/main/sources/libClangSharp

namespace ClangSharp.Interop;

public enum CX_OverloadedOperatorKind
{
    CX_OO_Invalid = 0,
    CX_OO_New = 1,
    CX_OO_Delete = 2,
    CX_OO_Array_New = 3,
    CX_OO_Array_Delete = 4,
    CX_OO_Plus = 5,
    CX_OO_Minus = 6,
    CX_OO_Star = 7,
    CX_OO_Slash = 8,
    CX_OO_Percent = 9,
    CX_OO_Caret = 10,
    CX_OO_Amp = 11,
    CX_OO_Pipe = 12,
    CX_OO_Tilde = 13,
    CX_OO_Exclaim = 14,
    CX_OO_Equal = 15,
    CX_OO_Less = 16,
    CX_OO_Greater = 17,
    CX_OO_PlusEqual = 18,
    CX_OO_MinusEqual = 19,
    CX_OO_StarEqual = 20,
    CX_OO_SlashEqual = 21,
    CX_OO_PercentEqual = 22,
    CX_OO_CaretEqual = 23,
    CX_OO_AmpEqual = 24,
    CX_OO_PipeEqual = 25,
    CX_OO_LessLess = 26,
    CX_OO_GreaterGreater = 27,
    CX_OO_LessLessEqual = 28,
    CX_OO_GreaterGreaterEqual = 29,
    CX_OO_EqualEqual = 30,
    CX_OO_ExclaimEqual = 31,
    CX_OO_LessEqual = 32,
    CX_OO_GreaterEqual = 33,
    CX_OO_Spaceship = 34,
    CX_OO_AmpAmp = 35,
    CX_OO_PipePipe = 36,
    CX_OO_PlusPlus = 37,
    CX_OO_MinusMinus = 38,
    CX_OO_Comma = 39,
    CX_OO_ArrowStar = 40,
    CX_OO_Arrow = 41,
    CX_OO_Call = 42,
    CX_OO_Subscript = 43,
    CX_OO_Conditional = 44,
    CX_OO_Coawait = 45,
}
